### ISSUE TITLE
Dwukrotna deklaracja tego samego obiektu

### ISSUE THREAD

**Issue by ceMigaming** [Serrwo/ITE-Java#1]
https://github.com/Serrwo/ITE-Java/wiki/Klasy -> pierwszy akapit

`  Student st1;
    Student st1;

    st1.name = "Jan Kowalski";
    st1.index_number = 273036;
    st1.age = 20;
    st1.grade = 3.5;

    st1.name = "Agata Wolkowska";
    st1.index_number = 304509;
    st1.age = 19;
    st1.grade = 4.75;`
poprawcie na:
`  Student st1;
    Student st2;

    st1.name = "Jan Kowalski";
    st1.index_number = 273036;
    st1.age = 20;
    st1.grade = 3.5;

    st2.name = "Agata Wolkowska";
    st2.index_number = 304509;
    st2.age = 19;
    st2.grade = 4.75;`
pozdro,
Maciek Chamera

**Comment by R3VANEK** [comment]
poprawione, dzięki za spota literówki
